// آزمون اصلاحات مشاور، جانمایی یک کاشی، شروع امن و پاداش دشمن
// آزمون راه‌اندازی، رابط، تأیید عملیات و قرارداد اتحاد با DOM شبیه‌سازی‌شده
const fs=require('fs'),vm=require('vm'),assert=require('assert');
class Node{
 constructor(){this.clientWidth=390;this.clientHeight=650;this.dataset={};this.style={setProperty(){}};this.listeners={};this.children=[];this.hidden=false;this.value='1';this.classList={s:new Set(),add(...x){x.forEach(v=>this.s.add(v))},remove(...x){x.forEach(v=>this.s.delete(v))},contains(x){return this.s.has(x)},toggle(x,b){const active=b??!this.s.has(x);active?this.s.add(x):this.s.delete(x);return active;}};}
 addEventListener(k,f){(this.listeners[k]??=[]).push(f)}
 insertAdjacentHTML(position,html){this.innerHTML=(this.innerHTML || "")+html;}
 remove(){} appendChild(x){this.children.push(x);return x}append(...x){this.children.push(...x)}replaceChildren(...x){this.children=x}setAttribute(k,v){this[k]=v}getAttribute(k){return this[k]||null}closest(){return null}focus(){}setPointerCapture(){}releasePointerCapture(){}
 querySelector(){return new Node()}querySelectorAll(){return []}getBoundingClientRect(){return {left:0,top:0,width:390,height:650,right:390,bottom:650}}
 getContext(){return new Proxy({createRadialGradient(){return {addColorStop(){}}}}, {get(o,k){return k in o?o[k]:(()=>{})}})}
}
const nodes=new Map();const document={getElementById(id){if(!nodes.has(id))nodes.set(id,new Node());return nodes.get(id)},querySelector(){return new Node()},querySelectorAll(){return []},createElement(){return new Node()},createElementNS(){return new Node()},addEventListener(){},body:new Node()};
class Img extends Node{constructor(){super();this.complete=false;this.naturalWidth=0;this.naturalHeight=0;}}
const local=new Map(),frames=[];let now=0;
const context={document,console,Date,Math,Map,Set,Uint8Array,Float32Array,Object,Array,Number,String,Promise,Image:Img,ResizeObserver:class{observe(){}},navigator:{deviceMemory:8},window:{devicePixelRatio:1,addEventListener(){},matchMedia(){return {matches:false}}},performance:{now:()=>now},localStorage:{setItem(k,v){local.set(k,v)},getItem(k){return local.get(k)||null},removeItem(k){local.delete(k)}},setTimeout(){return 1},setInterval(){return 1},clearTimeout(){},requestAnimationFrame(fn){frames.push(fn);return frames.length},cancelAnimationFrame(){}};
vm.createContext(context);let src=fs.readFileSync('assets/js/game.js','utf8');src=src.replace('  createCells();\n  loadAssets();','  globalThis.t={APP,state,startGame,createWorldMap,drawWorldMap,startMarch,mapToScreen,bindMapInput,teleportCastle,validTeleportTarget,recallCamp,insideEventArea,openInventory,openProfile,escapeHTML,renderMapActions,openMapTile,findSpawn,enemyLevel,enemyDropItem,enemies,ENEMY_TYPES,ensureStarterEnemy,resolveEnemyBattle,enemyRequirement,enemyResources,findMapRoute,occupiedTiles,footprintFits,canPlaceBuilding,empireAt,empireCenters,INVENTORY,showUITour,setNarratorText,advanceNarrator,setupTutorial,closePanels,updateMarches,saveGameProgress,loadGameProgress,drawTerritoryTerrain,terrainAtlas,productionMultiplier,productionRate,tickCollectors,collectResource,startArmyTask,tickArmy,TROOPS,TROOP_LINES,researchLine,troopUnlocked,troopStats,woundedStock,awardTablets,availableTablets,openTraining,openHealing,openResearch,openSettings,openSkins,openLeaderboard,openTroopsOverview,openBattleReport,startBranchResearch,queueMarkup,marchCapacity,startSecondBuild,tickAdditionalQueues,startResearch,finishTutorial,reserveTroops,respawnEnemies,enemySpaceFree,buildingDuration,buildingPower,buildingCost,MISSION_DATA};\n  createCells();\n  loadAssets();');vm.runInContext(src,context);

const t=context.t;t.startGame(true);t.APP.tutorial.active=false;t.createWorldMap();
(async()=>{
 assert.equal(t.TROOP_LINES.length,8);assert.equal(Object.keys(t.TROOPS).length,24);
 for(const b of t.state.buildings)assert(t.footprintFits(b,b.q,b.r),b.id);
 const byId=id=>t.state.buildings.find(b=>b.id===id);byId('barracks').level=10;byId('hospital').level=10;byId('research').level=10;byId('castle').level=10;
 for(const k of ['wood','food','stone','iron'])t.APP.resources[k]=10000000;
 document.getElementById('armyType').value='heavy';document.getElementById('armyCount').value='100';const food=t.APP.resources.food;t.startArmyTask('training');assert.equal(t.APP.army.training,null);assert.equal(t.APP.resources.food,food);
 t.awardTablets(20);t.awardTablets(2);t.awardTablets(20);assert.equal(t.availableTablets(),20);
 t.researchLine('archer').unlocked=true;t.APP.research.tabletsSpent=1;assert.equal(t.availableTablets(),19);
 const before=t.troopStats('archer').attack;const research=t.startBranchResearch('archer','attack');nodes.get('gameDialogActions').children.at(-1).listeners.click[0]();await research;assert.equal(t.APP.research.task.line,'archer');t.saveGameProgress();t.APP.research.task=null;t.loadGameProgress();assert.equal(t.APP.research.task.line,'archer');t.APP.research.task.endsAt=Date.now()-1;t.tickAdditionalQueues();assert(t.troopStats('archer').attack>before);t.tickAdditionalQueues();assert.equal(t.researchLine('archer').attack,1);
 // درمان چند رسته نوع هر مجروح را پس از ذخیره و تکمیل حفظ می‌کند.
 t.APP.army.wounded=5;t.APP.army.woundedUnits={sword:2,archer:3};t.APP.army.units={sword:10,archer:10};t.APP.army.troops=20;
 const originalQuery=document.querySelectorAll;document.querySelectorAll=selector=>selector==='[data-heal-count]'?[{dataset:{healCount:'sword'},value:'2',max:'2'},{dataset:{healCount:'archer'},value:'3',max:'3'}]:[];
 document.getElementById('armyCount').value='5';t.startArmyTask('healing');assert.equal(t.APP.army.healing.count,5);assert.equal(t.APP.army.wounded,0);assert.equal(t.APP.army.healing.units.archer,3);t.saveGameProgress();t.APP.army.healing=null;t.loadGameProgress();assert.equal(t.APP.army.healing.units.archer,3);t.APP.army.healing.endsAt=Date.now()-1;t.tickArmy();assert.equal(t.APP.army.units.archer,13);assert.equal(t.APP.army.units.sword,12);t.tickArmy();assert.equal(t.APP.army.troops,25);document.querySelectorAll=originalQuery;
 // کتیبه و پژوهش به عقب بازنمی‌گردند؛ تنظیمات و ظاهر هم ذخیره می‌شوند.
 t.APP.preferences={quality:'performance',sound:false};t.APP.skins={avatar:1,castle:2};t.saveGameProgress();t.APP.preferences={};t.APP.skins={};t.loadGameProgress();assert.equal(t.APP.preferences.quality,'performance');assert.equal(t.APP.skins.castle,2);assert.equal(t.availableTablets(),19);assert.equal(t.researchLine('archer').attack,1);
 // صف کارگر دوم سطح بالاتر بعد از بارگذاری ساختمان‌ها اعتبارسنجی می‌شود.
 t.APP.secondBuilder=true;byId('lumber').level=5;t.APP.worker2={task:{id:'lumber',target:6,startedAt:Date.now()},endsAt:Date.now()+100000};t.saveGameProgress();byId('lumber').level=0;t.APP.worker2={task:null,endsAt:0};t.loadGameProgress();assert.equal(t.APP.worker2.task.target,6);assert.equal(byId('lumber').level,5);
 // گزارش از ترکیب نبرد کپی می‌گیرد و تغییر لشکر سابق را تغییر نمی‌دهد.
 const march={id:'mixed-report',enemyId:'mixed-enemy',enemyLevel:1,enemyType:1,troops:20,combatPower:100000,unitCounts:{sword:10,archer:10},origin:{q:50,r:50},target:{q:51,r:50},arriveAt:Date.now()};t.resolveEnemyBattle(march,()=>1);const report=t.APP.battleReports.find(r=>r.id===march.id);assert(report);march.unitCounts.sword=0;assert.equal(report.units.sword,10);assert(report.defender.name);t.openBattleReport(report.id);assert(nodes.get('genericPanelContent').innerHTML.includes('battle-table'));
 for(const [fn,word] of [[t.openTraining,'data-start-army'],[t.openHealing,'heal'],[t.openResearch,'research-tree'],[t.openSettings,'data-setting'],[t.openTroopsOverview,'unit-grid'],[t.openLeaderboard,'data-rank'],[t.openSkins,'data-skin-kind']]){fn();assert(nodes.get('genericPanelContent').innerHTML.includes(word),word);}
 console.log('PASS: 8 troop lines/24 units, research locks/stat effects/save/completion, 20-tablet cap, mixed healing preservation/idempotency, second-worker migration, settings/skins persistence, immutable detailed reports and dedicated pages.');
})().catch(error=>{console.error(error);process.exitCode=1;});
