'use strict';
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const root = path.resolve(__dirname, '..');
function joinSources(directory) {
  return fs.readdirSync(path.join(root, directory)).sort()
    .filter(name => /\.(js|css)$/.test(name))
    .map(name => `\n/* Source: ${directory}/${name} */\n${fs.readFileSync(path.join(root, directory, name), 'utf8')}`)
    .join('\n');
}
const script = `/* Generated by npm run build. Edit src/js instead. */\n(() => {\n  "use strict";\n${joinSources('src/js')}\n})();\n`;
new vm.Script(script, { filename: 'game.js' });
for (const [name, content] of [
  ['assets/js/game.js', script],
  ['assets/css/game.css', `/* Generated by npm run build. Edit src/css instead. */\n${joinSources('src/css')}`],
]) {
  fs.mkdirSync(path.dirname(path.join(root, name)), { recursive: true });
  fs.writeFileSync(path.join(root, name), content);
}
console.log('Built game.js and game.css.');
